nats --server nats://localhost:4222 stream add --config infrastructure/nats/streams/auth-events.json
nats --server nats://localhost:4222 stream add --config infrastructure/nats/streams/order-events.json
nats --server nats://localhost:4222 stream add --config infrastructure/nats/streams/payment-events.json
